//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LMenu
        {
            get
            {
                return SteamVR_Actions.default_LMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean LGrip
        {
            get
            {
                return SteamVR_Actions.default_LGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean LTrigger
        {
            get
            {
                return SteamVR_Actions.default_LTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LTrackpad
        {
            get
            {
                return SteamVR_Actions.default_LTrackpad;
            }
        }
        
        public virtual SteamVR_Action_Pose LPose
        {
            get
            {
                return SteamVR_Actions.default_LPose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LTrackpadPos
        {
            get
            {
                return SteamVR_Actions.default_LTrackpadPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean RMenu
        {
            get
            {
                return SteamVR_Actions.default_RMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RGrip
        {
            get
            {
                return SteamVR_Actions.default_RGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean RTrigger
        {
            get
            {
                return SteamVR_Actions.default_RTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean RTrackpad
        {
            get
            {
                return SteamVR_Actions.default_RTrackpad;
            }
        }
        
        public virtual SteamVR_Action_Pose RPose
        {
            get
            {
                return SteamVR_Actions.default_RPose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RTrackpadPos
        {
            get
            {
                return SteamVR_Actions.default_RTrackpadPos;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
